# Generated by Django 5.1.3 on 2024-11-17 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=200, null=True, unique=True)),
                ('code', models.CharField(default=4, max_length=100, null=True)),
                ('logger_name', models.CharField(max_length=100)),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'NotSet'), (20, 'Info'), (30, 'Warning'), (10, 'Debug'), (40, 'Error'), (50, 'Fatal')], db_index=True, default=0)),
                ('msg', models.TextField()),
                ('trace', models.TextField(blank=True, null=True)),
                ('url', models.URLField(null=True)),
                ('request_time_start', models.DateTimeField(null=True, verbose_name='Created at')),
                ('request_time_end', models.DateTimeField(null=True)),
                ('duration', models.IntegerField(null=True, verbose_name='Duration in ms')),
                ('ip_address', models.CharField(max_length=25, null=True)),
                ('email_address', models.EmailField(max_length=254, null=True)),
                ('hijacker', models.CharField(max_length=40, null=True)),
                ('parameters', models.TextField(null=True)),
                ('hijacked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Request Log',
                'verbose_name_plural': 'Request Logs',
                'ordering': ('-request_time_start',),
            },
        ),
    ]
